joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 500

mobile_base_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: ['front_left_wheel_joint', 'rear_left_wheel_joint']
  right_wheel: ['front_right_wheel_joint', 'rear_right_wheel_joint']
  publish_rate: 500
  pose_covariance_diagonal : [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]
  
  cmd_vel_timeout: 0.05

  # Odometry fused with IMU is published by robot_localization, so
  # no need to publish a TF based on encoders alone.
  enable_odom_tf: true

  # wheel_separation_x: 0.18
  # wheel_separation_y: 0.27
  # wheel_radius: 0.051  # 8cm

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : false
      max_velocity           : 0.1   # m/s
      has_acceleration_limits: false
      max_acceleration       : 3.0   # m/s^2
  angular:
    z:
      has_velocity_limits    : false
      max_velocity           : 5.0   # rad/s
      has_acceleration_limits: false
      max_acceleration       : 10.0   # rad/s^2

# /gazebo_ros_control:
#      pid_gains:
#        front_left_wheel_joint: {p: 20.0, i: 0.01, d: 0.0}
#        front_right_wheel_joint: {p: 20.0, i: 0.01, d: 0.0}
#        rear_left_wheel_joint: {p: 20.0, i: 0.01, d: 0.0}
#        rear_right_wheel_joint: {p: 20.0, i: 0.01, d: 0.0}