// Generated by gencpp from file mirte_msgs/get_barcode.msg
// DO NOT EDIT!


#ifndef MIRTE_MSGS_MESSAGE_GET_BARCODE_H
#define MIRTE_MSGS_MESSAGE_GET_BARCODE_H

#include <ros/service_traits.h>


#include <mirte_msgs/get_barcodeRequest.h>
#include <mirte_msgs/get_barcodeResponse.h>


namespace mirte_msgs
{

struct get_barcode
{

typedef get_barcodeRequest Request;
typedef get_barcodeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct get_barcode
} // namespace mirte_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mirte_msgs::get_barcode > {
  static const char* value()
  {
    return "992ce8a1687cec8c8bd883ec73ca41d1";
  }

  static const char* value(const ::mirte_msgs::get_barcode&) { return value(); }
};

template<>
struct DataType< ::mirte_msgs::get_barcode > {
  static const char* value()
  {
    return "mirte_msgs/get_barcode";
  }

  static const char* value(const ::mirte_msgs::get_barcode&) { return value(); }
};


// service_traits::MD5Sum< ::mirte_msgs::get_barcodeRequest> should match
// service_traits::MD5Sum< ::mirte_msgs::get_barcode >
template<>
struct MD5Sum< ::mirte_msgs::get_barcodeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mirte_msgs::get_barcode >::value();
  }
  static const char* value(const ::mirte_msgs::get_barcodeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirte_msgs::get_barcodeRequest> should match
// service_traits::DataType< ::mirte_msgs::get_barcode >
template<>
struct DataType< ::mirte_msgs::get_barcodeRequest>
{
  static const char* value()
  {
    return DataType< ::mirte_msgs::get_barcode >::value();
  }
  static const char* value(const ::mirte_msgs::get_barcodeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mirte_msgs::get_barcodeResponse> should match
// service_traits::MD5Sum< ::mirte_msgs::get_barcode >
template<>
struct MD5Sum< ::mirte_msgs::get_barcodeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mirte_msgs::get_barcode >::value();
  }
  static const char* value(const ::mirte_msgs::get_barcodeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirte_msgs::get_barcodeResponse> should match
// service_traits::DataType< ::mirte_msgs::get_barcode >
template<>
struct DataType< ::mirte_msgs::get_barcodeResponse>
{
  static const char* value()
  {
    return DataType< ::mirte_msgs::get_barcode >::value();
  }
  static const char* value(const ::mirte_msgs::get_barcodeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MIRTE_MSGS_MESSAGE_GET_BARCODE_H
