// Generated by gencpp from file mirte_msgs/GetDistance.msg
// DO NOT EDIT!


#ifndef MIRTE_MSGS_MESSAGE_GETDISTANCE_H
#define MIRTE_MSGS_MESSAGE_GETDISTANCE_H

#include <ros/service_traits.h>


#include <mirte_msgs/GetDistanceRequest.h>
#include <mirte_msgs/GetDistanceResponse.h>


namespace mirte_msgs
{

struct GetDistance
{

typedef GetDistanceRequest Request;
typedef GetDistanceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetDistance
} // namespace mirte_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mirte_msgs::GetDistance > {
  static const char* value()
  {
    return "73fcbf46b49191e672908e50842a83d4";
  }

  static const char* value(const ::mirte_msgs::GetDistance&) { return value(); }
};

template<>
struct DataType< ::mirte_msgs::GetDistance > {
  static const char* value()
  {
    return "mirte_msgs/GetDistance";
  }

  static const char* value(const ::mirte_msgs::GetDistance&) { return value(); }
};


// service_traits::MD5Sum< ::mirte_msgs::GetDistanceRequest> should match
// service_traits::MD5Sum< ::mirte_msgs::GetDistance >
template<>
struct MD5Sum< ::mirte_msgs::GetDistanceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mirte_msgs::GetDistance >::value();
  }
  static const char* value(const ::mirte_msgs::GetDistanceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirte_msgs::GetDistanceRequest> should match
// service_traits::DataType< ::mirte_msgs::GetDistance >
template<>
struct DataType< ::mirte_msgs::GetDistanceRequest>
{
  static const char* value()
  {
    return DataType< ::mirte_msgs::GetDistance >::value();
  }
  static const char* value(const ::mirte_msgs::GetDistanceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mirte_msgs::GetDistanceResponse> should match
// service_traits::MD5Sum< ::mirte_msgs::GetDistance >
template<>
struct MD5Sum< ::mirte_msgs::GetDistanceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mirte_msgs::GetDistance >::value();
  }
  static const char* value(const ::mirte_msgs::GetDistanceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirte_msgs::GetDistanceResponse> should match
// service_traits::DataType< ::mirte_msgs::GetDistance >
template<>
struct DataType< ::mirte_msgs::GetDistanceResponse>
{
  static const char* value()
  {
    return DataType< ::mirte_msgs::GetDistance >::value();
  }
  static const char* value(const ::mirte_msgs::GetDistanceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MIRTE_MSGS_MESSAGE_GETDISTANCE_H
