// Generated by gencpp from file mirte_msgs/GetIntensityResponse.msg
// DO NOT EDIT!


#ifndef MIRTE_MSGS_MESSAGE_GETINTENSITYRESPONSE_H
#define MIRTE_MSGS_MESSAGE_GETINTENSITYRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mirte_msgs
{
template <class ContainerAllocator>
struct GetIntensityResponse_
{
  typedef GetIntensityResponse_<ContainerAllocator> Type;

  GetIntensityResponse_()
    : data(0)  {
    }
  GetIntensityResponse_(const ContainerAllocator& _alloc)
    : data(0)  {
  (void)_alloc;
    }



   typedef int32_t _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::mirte_msgs::GetIntensityResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mirte_msgs::GetIntensityResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetIntensityResponse_

typedef ::mirte_msgs::GetIntensityResponse_<std::allocator<void> > GetIntensityResponse;

typedef boost::shared_ptr< ::mirte_msgs::GetIntensityResponse > GetIntensityResponsePtr;
typedef boost::shared_ptr< ::mirte_msgs::GetIntensityResponse const> GetIntensityResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mirte_msgs::GetIntensityResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mirte_msgs::GetIntensityResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mirte_msgs::GetIntensityResponse_<ContainerAllocator1> & lhs, const ::mirte_msgs::GetIntensityResponse_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mirte_msgs::GetIntensityResponse_<ContainerAllocator1> & lhs, const ::mirte_msgs::GetIntensityResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mirte_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mirte_msgs::GetIntensityResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mirte_msgs::GetIntensityResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mirte_msgs::GetIntensityResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mirte_msgs::GetIntensityResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mirte_msgs::GetIntensityResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mirte_msgs::GetIntensityResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mirte_msgs::GetIntensityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "da5909fbe378aeaf85e547e830cc1bb7";
  }

  static const char* value(const ::mirte_msgs::GetIntensityResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xda5909fbe378aeafULL;
  static const uint64_t static_value2 = 0x85e547e830cc1bb7ULL;
};

template<class ContainerAllocator>
struct DataType< ::mirte_msgs::GetIntensityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mirte_msgs/GetIntensityResponse";
  }

  static const char* value(const ::mirte_msgs::GetIntensityResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mirte_msgs::GetIntensityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 data\n"
"\n"
;
  }

  static const char* value(const ::mirte_msgs::GetIntensityResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mirte_msgs::GetIntensityResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetIntensityResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mirte_msgs::GetIntensityResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mirte_msgs::GetIntensityResponse_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<int32_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MIRTE_MSGS_MESSAGE_GETINTENSITYRESPONSE_H
