// Generated by gencpp from file mirte_msgs/GetIntensity.msg
// DO NOT EDIT!


#ifndef MIRTE_MSGS_MESSAGE_GETINTENSITY_H
#define MIRTE_MSGS_MESSAGE_GETINTENSITY_H

#include <ros/service_traits.h>


#include <mirte_msgs/GetIntensityRequest.h>
#include <mirte_msgs/GetIntensityResponse.h>


namespace mirte_msgs
{

struct GetIntensity
{

typedef GetIntensityRequest Request;
typedef GetIntensityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetIntensity
} // namespace mirte_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mirte_msgs::GetIntensity > {
  static const char* value()
  {
    return "da5909fbe378aeaf85e547e830cc1bb7";
  }

  static const char* value(const ::mirte_msgs::GetIntensity&) { return value(); }
};

template<>
struct DataType< ::mirte_msgs::GetIntensity > {
  static const char* value()
  {
    return "mirte_msgs/GetIntensity";
  }

  static const char* value(const ::mirte_msgs::GetIntensity&) { return value(); }
};


// service_traits::MD5Sum< ::mirte_msgs::GetIntensityRequest> should match
// service_traits::MD5Sum< ::mirte_msgs::GetIntensity >
template<>
struct MD5Sum< ::mirte_msgs::GetIntensityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mirte_msgs::GetIntensity >::value();
  }
  static const char* value(const ::mirte_msgs::GetIntensityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirte_msgs::GetIntensityRequest> should match
// service_traits::DataType< ::mirte_msgs::GetIntensity >
template<>
struct DataType< ::mirte_msgs::GetIntensityRequest>
{
  static const char* value()
  {
    return DataType< ::mirte_msgs::GetIntensity >::value();
  }
  static const char* value(const ::mirte_msgs::GetIntensityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mirte_msgs::GetIntensityResponse> should match
// service_traits::MD5Sum< ::mirte_msgs::GetIntensity >
template<>
struct MD5Sum< ::mirte_msgs::GetIntensityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mirte_msgs::GetIntensity >::value();
  }
  static const char* value(const ::mirte_msgs::GetIntensityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirte_msgs::GetIntensityResponse> should match
// service_traits::DataType< ::mirte_msgs::GetIntensity >
template<>
struct DataType< ::mirte_msgs::GetIntensityResponse>
{
  static const char* value()
  {
    return DataType< ::mirte_msgs::GetIntensity >::value();
  }
  static const char* value(const ::mirte_msgs::GetIntensityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MIRTE_MSGS_MESSAGE_GETINTENSITY_H
