// Generated by gencpp from file mirte_msgs/GetIntensityDigitalResponse.msg
// DO NOT EDIT!


#ifndef MIRTE_MSGS_MESSAGE_GETINTENSITYDIGITALRESPONSE_H
#define MIRTE_MSGS_MESSAGE_GETINTENSITYDIGITALRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mirte_msgs
{
template <class ContainerAllocator>
struct GetIntensityDigitalResponse_
{
  typedef GetIntensityDigitalResponse_<ContainerAllocator> Type;

  GetIntensityDigitalResponse_()
    : data(false)  {
    }
  GetIntensityDigitalResponse_(const ContainerAllocator& _alloc)
    : data(false)  {
  (void)_alloc;
    }



   typedef uint8_t _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::mirte_msgs::GetIntensityDigitalResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mirte_msgs::GetIntensityDigitalResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetIntensityDigitalResponse_

typedef ::mirte_msgs::GetIntensityDigitalResponse_<std::allocator<void> > GetIntensityDigitalResponse;

typedef boost::shared_ptr< ::mirte_msgs::GetIntensityDigitalResponse > GetIntensityDigitalResponsePtr;
typedef boost::shared_ptr< ::mirte_msgs::GetIntensityDigitalResponse const> GetIntensityDigitalResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mirte_msgs::GetIntensityDigitalResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mirte_msgs::GetIntensityDigitalResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mirte_msgs::GetIntensityDigitalResponse_<ContainerAllocator1> & lhs, const ::mirte_msgs::GetIntensityDigitalResponse_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mirte_msgs::GetIntensityDigitalResponse_<ContainerAllocator1> & lhs, const ::mirte_msgs::GetIntensityDigitalResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mirte_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mirte_msgs::GetIntensityDigitalResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mirte_msgs::GetIntensityDigitalResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mirte_msgs::GetIntensityDigitalResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mirte_msgs::GetIntensityDigitalResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mirte_msgs::GetIntensityDigitalResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mirte_msgs::GetIntensityDigitalResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mirte_msgs::GetIntensityDigitalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8b94c1b53db61fb6aed406028ad6332a";
  }

  static const char* value(const ::mirte_msgs::GetIntensityDigitalResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8b94c1b53db61fb6ULL;
  static const uint64_t static_value2 = 0xaed406028ad6332aULL;
};

template<class ContainerAllocator>
struct DataType< ::mirte_msgs::GetIntensityDigitalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mirte_msgs/GetIntensityDigitalResponse";
  }

  static const char* value(const ::mirte_msgs::GetIntensityDigitalResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mirte_msgs::GetIntensityDigitalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool data\n"
"\n"
;
  }

  static const char* value(const ::mirte_msgs::GetIntensityDigitalResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mirte_msgs::GetIntensityDigitalResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetIntensityDigitalResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mirte_msgs::GetIntensityDigitalResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mirte_msgs::GetIntensityDigitalResponse_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MIRTE_MSGS_MESSAGE_GETINTENSITYDIGITALRESPONSE_H
