// Generated by gencpp from file mirte_msgs/GetKeypad.msg
// DO NOT EDIT!


#ifndef MIRTE_MSGS_MESSAGE_GETKEYPAD_H
#define MIRTE_MSGS_MESSAGE_GETKEYPAD_H

#include <ros/service_traits.h>


#include <mirte_msgs/GetKeypadRequest.h>
#include <mirte_msgs/GetKeypadResponse.h>


namespace mirte_msgs
{

struct GetKeypad
{

typedef GetKeypadRequest Request;
typedef GetKeypadResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetKeypad
} // namespace mirte_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mirte_msgs::GetKeypad > {
  static const char* value()
  {
    return "992ce8a1687cec8c8bd883ec73ca41d1";
  }

  static const char* value(const ::mirte_msgs::GetKeypad&) { return value(); }
};

template<>
struct DataType< ::mirte_msgs::GetKeypad > {
  static const char* value()
  {
    return "mirte_msgs/GetKeypad";
  }

  static const char* value(const ::mirte_msgs::GetKeypad&) { return value(); }
};


// service_traits::MD5Sum< ::mirte_msgs::GetKeypadRequest> should match
// service_traits::MD5Sum< ::mirte_msgs::GetKeypad >
template<>
struct MD5Sum< ::mirte_msgs::GetKeypadRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mirte_msgs::GetKeypad >::value();
  }
  static const char* value(const ::mirte_msgs::GetKeypadRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirte_msgs::GetKeypadRequest> should match
// service_traits::DataType< ::mirte_msgs::GetKeypad >
template<>
struct DataType< ::mirte_msgs::GetKeypadRequest>
{
  static const char* value()
  {
    return DataType< ::mirte_msgs::GetKeypad >::value();
  }
  static const char* value(const ::mirte_msgs::GetKeypadRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mirte_msgs::GetKeypadResponse> should match
// service_traits::MD5Sum< ::mirte_msgs::GetKeypad >
template<>
struct MD5Sum< ::mirte_msgs::GetKeypadResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mirte_msgs::GetKeypad >::value();
  }
  static const char* value(const ::mirte_msgs::GetKeypadResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirte_msgs::GetKeypadResponse> should match
// service_traits::DataType< ::mirte_msgs::GetKeypad >
template<>
struct DataType< ::mirte_msgs::GetKeypadResponse>
{
  static const char* value()
  {
    return DataType< ::mirte_msgs::GetKeypad >::value();
  }
  static const char* value(const ::mirte_msgs::GetKeypadResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MIRTE_MSGS_MESSAGE_GETKEYPAD_H
