// Generated by gencpp from file mirte_msgs/GetKeypadRequest.msg
// DO NOT EDIT!


#ifndef MIRTE_MSGS_MESSAGE_GETKEYPADREQUEST_H
#define MIRTE_MSGS_MESSAGE_GETKEYPADREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mirte_msgs
{
template <class ContainerAllocator>
struct GetKeypadRequest_
{
  typedef GetKeypadRequest_<ContainerAllocator> Type;

  GetKeypadRequest_()
    {
    }
  GetKeypadRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::mirte_msgs::GetKeypadRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mirte_msgs::GetKeypadRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetKeypadRequest_

typedef ::mirte_msgs::GetKeypadRequest_<std::allocator<void> > GetKeypadRequest;

typedef boost::shared_ptr< ::mirte_msgs::GetKeypadRequest > GetKeypadRequestPtr;
typedef boost::shared_ptr< ::mirte_msgs::GetKeypadRequest const> GetKeypadRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mirte_msgs::GetKeypadRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mirte_msgs::GetKeypadRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace mirte_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mirte_msgs::GetKeypadRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mirte_msgs::GetKeypadRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mirte_msgs::GetKeypadRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mirte_msgs::GetKeypadRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mirte_msgs::GetKeypadRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mirte_msgs::GetKeypadRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mirte_msgs::GetKeypadRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::mirte_msgs::GetKeypadRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::mirte_msgs::GetKeypadRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mirte_msgs/GetKeypadRequest";
  }

  static const char* value(const ::mirte_msgs::GetKeypadRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mirte_msgs::GetKeypadRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::mirte_msgs::GetKeypadRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mirte_msgs::GetKeypadRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetKeypadRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mirte_msgs::GetKeypadRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::mirte_msgs::GetKeypadRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MIRTE_MSGS_MESSAGE_GETKEYPADREQUEST_H
