// Generated by gencpp from file mirte_msgs/GetPinValue.msg
// DO NOT EDIT!


#ifndef MIRTE_MSGS_MESSAGE_GETPINVALUE_H
#define MIRTE_MSGS_MESSAGE_GETPINVALUE_H

#include <ros/service_traits.h>


#include <mirte_msgs/GetPinValueRequest.h>
#include <mirte_msgs/GetPinValueResponse.h>


namespace mirte_msgs
{

struct GetPinValue
{

typedef GetPinValueRequest Request;
typedef GetPinValueResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPinValue
} // namespace mirte_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mirte_msgs::GetPinValue > {
  static const char* value()
  {
    return "277ba96458b48c83913177a820e47af8";
  }

  static const char* value(const ::mirte_msgs::GetPinValue&) { return value(); }
};

template<>
struct DataType< ::mirte_msgs::GetPinValue > {
  static const char* value()
  {
    return "mirte_msgs/GetPinValue";
  }

  static const char* value(const ::mirte_msgs::GetPinValue&) { return value(); }
};


// service_traits::MD5Sum< ::mirte_msgs::GetPinValueRequest> should match
// service_traits::MD5Sum< ::mirte_msgs::GetPinValue >
template<>
struct MD5Sum< ::mirte_msgs::GetPinValueRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mirte_msgs::GetPinValue >::value();
  }
  static const char* value(const ::mirte_msgs::GetPinValueRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirte_msgs::GetPinValueRequest> should match
// service_traits::DataType< ::mirte_msgs::GetPinValue >
template<>
struct DataType< ::mirte_msgs::GetPinValueRequest>
{
  static const char* value()
  {
    return DataType< ::mirte_msgs::GetPinValue >::value();
  }
  static const char* value(const ::mirte_msgs::GetPinValueRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mirte_msgs::GetPinValueResponse> should match
// service_traits::MD5Sum< ::mirte_msgs::GetPinValue >
template<>
struct MD5Sum< ::mirte_msgs::GetPinValueResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mirte_msgs::GetPinValue >::value();
  }
  static const char* value(const ::mirte_msgs::GetPinValueResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirte_msgs::GetPinValueResponse> should match
// service_traits::DataType< ::mirte_msgs::GetPinValue >
template<>
struct DataType< ::mirte_msgs::GetPinValueResponse>
{
  static const char* value()
  {
    return DataType< ::mirte_msgs::GetPinValue >::value();
  }
  static const char* value(const ::mirte_msgs::GetPinValueResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MIRTE_MSGS_MESSAGE_GETPINVALUE_H
