// Generated by gencpp from file mirte_msgs/GetRange.msg
// DO NOT EDIT!


#ifndef MIRTE_MSGS_MESSAGE_GETRANGE_H
#define MIRTE_MSGS_MESSAGE_GETRANGE_H

#include <ros/service_traits.h>


#include <mirte_msgs/GetRangeRequest.h>
#include <mirte_msgs/GetRangeResponse.h>


namespace mirte_msgs
{

struct GetRange
{

typedef GetRangeRequest Request;
typedef GetRangeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetRange
} // namespace mirte_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mirte_msgs::GetRange > {
  static const char* value()
  {
    return "b3ee9ed25575b46bb47c7673ad202faa";
  }

  static const char* value(const ::mirte_msgs::GetRange&) { return value(); }
};

template<>
struct DataType< ::mirte_msgs::GetRange > {
  static const char* value()
  {
    return "mirte_msgs/GetRange";
  }

  static const char* value(const ::mirte_msgs::GetRange&) { return value(); }
};


// service_traits::MD5Sum< ::mirte_msgs::GetRangeRequest> should match
// service_traits::MD5Sum< ::mirte_msgs::GetRange >
template<>
struct MD5Sum< ::mirte_msgs::GetRangeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mirte_msgs::GetRange >::value();
  }
  static const char* value(const ::mirte_msgs::GetRangeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirte_msgs::GetRangeRequest> should match
// service_traits::DataType< ::mirte_msgs::GetRange >
template<>
struct DataType< ::mirte_msgs::GetRangeRequest>
{
  static const char* value()
  {
    return DataType< ::mirte_msgs::GetRange >::value();
  }
  static const char* value(const ::mirte_msgs::GetRangeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mirte_msgs::GetRangeResponse> should match
// service_traits::MD5Sum< ::mirte_msgs::GetRange >
template<>
struct MD5Sum< ::mirte_msgs::GetRangeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mirte_msgs::GetRange >::value();
  }
  static const char* value(const ::mirte_msgs::GetRangeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirte_msgs::GetRangeResponse> should match
// service_traits::DataType< ::mirte_msgs::GetRange >
template<>
struct DataType< ::mirte_msgs::GetRangeResponse>
{
  static const char* value()
  {
    return DataType< ::mirte_msgs::GetRange >::value();
  }
  static const char* value(const ::mirte_msgs::GetRangeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MIRTE_MSGS_MESSAGE_GETRANGE_H
