// Generated by gencpp from file mirte_msgs/GetRangeResponse.msg
// DO NOT EDIT!


#ifndef MIRTE_MSGS_MESSAGE_GETRANGERESPONSE_H
#define MIRTE_MSGS_MESSAGE_GETRANGERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mirte_msgs
{
template <class ContainerAllocator>
struct GetRangeResponse_
{
  typedef GetRangeResponse_<ContainerAllocator> Type;

  GetRangeResponse_()
    : min(0.0)
    , max(0.0)  {
    }
  GetRangeResponse_(const ContainerAllocator& _alloc)
    : min(0.0)
    , max(0.0)  {
  (void)_alloc;
    }



   typedef float _min_type;
  _min_type min;

   typedef float _max_type;
  _max_type max;





  typedef boost::shared_ptr< ::mirte_msgs::GetRangeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mirte_msgs::GetRangeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetRangeResponse_

typedef ::mirte_msgs::GetRangeResponse_<std::allocator<void> > GetRangeResponse;

typedef boost::shared_ptr< ::mirte_msgs::GetRangeResponse > GetRangeResponsePtr;
typedef boost::shared_ptr< ::mirte_msgs::GetRangeResponse const> GetRangeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mirte_msgs::GetRangeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mirte_msgs::GetRangeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mirte_msgs::GetRangeResponse_<ContainerAllocator1> & lhs, const ::mirte_msgs::GetRangeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.min == rhs.min &&
    lhs.max == rhs.max;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mirte_msgs::GetRangeResponse_<ContainerAllocator1> & lhs, const ::mirte_msgs::GetRangeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mirte_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mirte_msgs::GetRangeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mirte_msgs::GetRangeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mirte_msgs::GetRangeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mirte_msgs::GetRangeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mirte_msgs::GetRangeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mirte_msgs::GetRangeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mirte_msgs::GetRangeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b3ee9ed25575b46bb47c7673ad202faa";
  }

  static const char* value(const ::mirte_msgs::GetRangeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb3ee9ed25575b46bULL;
  static const uint64_t static_value2 = 0xb47c7673ad202faaULL;
};

template<class ContainerAllocator>
struct DataType< ::mirte_msgs::GetRangeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mirte_msgs/GetRangeResponse";
  }

  static const char* value(const ::mirte_msgs::GetRangeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mirte_msgs::GetRangeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 min\n"
"float32 max\n"
;
  }

  static const char* value(const ::mirte_msgs::GetRangeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mirte_msgs::GetRangeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.min);
      stream.next(m.max);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetRangeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mirte_msgs::GetRangeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mirte_msgs::GetRangeResponse_<ContainerAllocator>& v)
  {
    s << indent << "min: ";
    Printer<float>::stream(s, indent + "  ", v.min);
    s << indent << "max: ";
    Printer<float>::stream(s, indent + "  ", v.max);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MIRTE_MSGS_MESSAGE_GETRANGERESPONSE_H
