// Generated by gencpp from file mirte_msgs/Intensity.msg
// DO NOT EDIT!


#ifndef MIRTE_MSGS_MESSAGE_INTENSITY_H
#define MIRTE_MSGS_MESSAGE_INTENSITY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace mirte_msgs
{
template <class ContainerAllocator>
struct Intensity_
{
  typedef Intensity_<ContainerAllocator> Type;

  Intensity_()
    : header()
    , value(0)  {
    }
  Intensity_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , value(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::mirte_msgs::Intensity_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mirte_msgs::Intensity_<ContainerAllocator> const> ConstPtr;

}; // struct Intensity_

typedef ::mirte_msgs::Intensity_<std::allocator<void> > Intensity;

typedef boost::shared_ptr< ::mirte_msgs::Intensity > IntensityPtr;
typedef boost::shared_ptr< ::mirte_msgs::Intensity const> IntensityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mirte_msgs::Intensity_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mirte_msgs::Intensity_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mirte_msgs::Intensity_<ContainerAllocator1> & lhs, const ::mirte_msgs::Intensity_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mirte_msgs::Intensity_<ContainerAllocator1> & lhs, const ::mirte_msgs::Intensity_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mirte_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mirte_msgs::Intensity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mirte_msgs::Intensity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mirte_msgs::Intensity_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mirte_msgs::Intensity_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mirte_msgs::Intensity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mirte_msgs::Intensity_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mirte_msgs::Intensity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f231299e824089b22a987717bd7ace62";
  }

  static const char* value(const ::mirte_msgs::Intensity_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf231299e824089b2ULL;
  static const uint64_t static_value2 = 0x2a987717bd7ace62ULL;
};

template<class ContainerAllocator>
struct DataType< ::mirte_msgs::Intensity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mirte_msgs/Intensity";
  }

  static const char* value(const ::mirte_msgs::Intensity_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mirte_msgs::Intensity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int32 value\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::mirte_msgs::Intensity_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mirte_msgs::Intensity_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Intensity_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mirte_msgs::Intensity_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mirte_msgs::Intensity_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "value: ";
    Printer<int32_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MIRTE_MSGS_MESSAGE_INTENSITY_H
