// Generated by gencpp from file mirte_msgs/Keypad.msg
// DO NOT EDIT!


#ifndef MIRTE_MSGS_MESSAGE_KEYPAD_H
#define MIRTE_MSGS_MESSAGE_KEYPAD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace mirte_msgs
{
template <class ContainerAllocator>
struct Keypad_
{
  typedef Keypad_<ContainerAllocator> Type;

  Keypad_()
    : header()
    , key()  {
    }
  Keypad_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , key(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _key_type;
  _key_type key;





  typedef boost::shared_ptr< ::mirte_msgs::Keypad_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mirte_msgs::Keypad_<ContainerAllocator> const> ConstPtr;

}; // struct Keypad_

typedef ::mirte_msgs::Keypad_<std::allocator<void> > Keypad;

typedef boost::shared_ptr< ::mirte_msgs::Keypad > KeypadPtr;
typedef boost::shared_ptr< ::mirte_msgs::Keypad const> KeypadConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mirte_msgs::Keypad_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mirte_msgs::Keypad_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mirte_msgs::Keypad_<ContainerAllocator1> & lhs, const ::mirte_msgs::Keypad_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.key == rhs.key;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mirte_msgs::Keypad_<ContainerAllocator1> & lhs, const ::mirte_msgs::Keypad_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mirte_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mirte_msgs::Keypad_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mirte_msgs::Keypad_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mirte_msgs::Keypad_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mirte_msgs::Keypad_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mirte_msgs::Keypad_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mirte_msgs::Keypad_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mirte_msgs::Keypad_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3af5b3f309206fb790d169ed56f35fad";
  }

  static const char* value(const ::mirte_msgs::Keypad_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3af5b3f309206fb7ULL;
  static const uint64_t static_value2 = 0x90d169ed56f35fadULL;
};

template<class ContainerAllocator>
struct DataType< ::mirte_msgs::Keypad_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mirte_msgs/Keypad";
  }

  static const char* value(const ::mirte_msgs::Keypad_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mirte_msgs::Keypad_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"string key\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::mirte_msgs::Keypad_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mirte_msgs::Keypad_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.key);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Keypad_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mirte_msgs::Keypad_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mirte_msgs::Keypad_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "key: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.key);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MIRTE_MSGS_MESSAGE_KEYPAD_H
