// Generated by gencpp from file mirte_msgs/Move.msg
// DO NOT EDIT!


#ifndef MIRTE_MSGS_MESSAGE_MOVE_H
#define MIRTE_MSGS_MESSAGE_MOVE_H

#include <ros/service_traits.h>


#include <mirte_msgs/MoveRequest.h>
#include <mirte_msgs/MoveResponse.h>


namespace mirte_msgs
{

struct Move
{

typedef MoveRequest Request;
typedef MoveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Move
} // namespace mirte_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mirte_msgs::Move > {
  static const char* value()
  {
    return "6b4f1d96a2bee68005f89c9b5b4fba0d";
  }

  static const char* value(const ::mirte_msgs::Move&) { return value(); }
};

template<>
struct DataType< ::mirte_msgs::Move > {
  static const char* value()
  {
    return "mirte_msgs/Move";
  }

  static const char* value(const ::mirte_msgs::Move&) { return value(); }
};


// service_traits::MD5Sum< ::mirte_msgs::MoveRequest> should match
// service_traits::MD5Sum< ::mirte_msgs::Move >
template<>
struct MD5Sum< ::mirte_msgs::MoveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mirte_msgs::Move >::value();
  }
  static const char* value(const ::mirte_msgs::MoveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirte_msgs::MoveRequest> should match
// service_traits::DataType< ::mirte_msgs::Move >
template<>
struct DataType< ::mirte_msgs::MoveRequest>
{
  static const char* value()
  {
    return DataType< ::mirte_msgs::Move >::value();
  }
  static const char* value(const ::mirte_msgs::MoveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mirte_msgs::MoveResponse> should match
// service_traits::MD5Sum< ::mirte_msgs::Move >
template<>
struct MD5Sum< ::mirte_msgs::MoveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mirte_msgs::Move >::value();
  }
  static const char* value(const ::mirte_msgs::MoveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirte_msgs::MoveResponse> should match
// service_traits::DataType< ::mirte_msgs::Move >
template<>
struct DataType< ::mirte_msgs::MoveResponse>
{
  static const char* value()
  {
    return DataType< ::mirte_msgs::Move >::value();
  }
  static const char* value(const ::mirte_msgs::MoveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MIRTE_MSGS_MESSAGE_MOVE_H
