// Generated by gencpp from file mirte_msgs/ServoPosition.msg
// DO NOT EDIT!


#ifndef MIRTE_MSGS_MESSAGE_SERVOPOSITION_H
#define MIRTE_MSGS_MESSAGE_SERVOPOSITION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace mirte_msgs
{
template <class ContainerAllocator>
struct ServoPosition_
{
  typedef ServoPosition_<ContainerAllocator> Type;

  ServoPosition_()
    : header()
    , angle(0.0)
    , raw(0)  {
    }
  ServoPosition_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , angle(0.0)
    , raw(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _angle_type;
  _angle_type angle;

   typedef int32_t _raw_type;
  _raw_type raw;





  typedef boost::shared_ptr< ::mirte_msgs::ServoPosition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mirte_msgs::ServoPosition_<ContainerAllocator> const> ConstPtr;

}; // struct ServoPosition_

typedef ::mirte_msgs::ServoPosition_<std::allocator<void> > ServoPosition;

typedef boost::shared_ptr< ::mirte_msgs::ServoPosition > ServoPositionPtr;
typedef boost::shared_ptr< ::mirte_msgs::ServoPosition const> ServoPositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mirte_msgs::ServoPosition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mirte_msgs::ServoPosition_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mirte_msgs::ServoPosition_<ContainerAllocator1> & lhs, const ::mirte_msgs::ServoPosition_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.angle == rhs.angle &&
    lhs.raw == rhs.raw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mirte_msgs::ServoPosition_<ContainerAllocator1> & lhs, const ::mirte_msgs::ServoPosition_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mirte_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mirte_msgs::ServoPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mirte_msgs::ServoPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mirte_msgs::ServoPosition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mirte_msgs::ServoPosition_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mirte_msgs::ServoPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mirte_msgs::ServoPosition_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mirte_msgs::ServoPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "02c45719e1552fa22bb3a7a6316fe73b";
  }

  static const char* value(const ::mirte_msgs::ServoPosition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x02c45719e1552fa2ULL;
  static const uint64_t static_value2 = 0x2bb3a7a6316fe73bULL;
};

template<class ContainerAllocator>
struct DataType< ::mirte_msgs::ServoPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mirte_msgs/ServoPosition";
  }

  static const char* value(const ::mirte_msgs::ServoPosition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mirte_msgs::ServoPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32 angle\n"
"int32 raw\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::mirte_msgs::ServoPosition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mirte_msgs::ServoPosition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.angle);
      stream.next(m.raw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServoPosition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mirte_msgs::ServoPosition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mirte_msgs::ServoPosition_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
    s << indent << "raw: ";
    Printer<int32_t>::stream(s, indent + "  ", v.raw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MIRTE_MSGS_MESSAGE_SERVOPOSITION_H
