// Generated by gencpp from file mirte_msgs/SetLEDValueRequest.msg
// DO NOT EDIT!


#ifndef MIRTE_MSGS_MESSAGE_SETLEDVALUEREQUEST_H
#define MIRTE_MSGS_MESSAGE_SETLEDVALUEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mirte_msgs
{
template <class ContainerAllocator>
struct SetLEDValueRequest_
{
  typedef SetLEDValueRequest_<ContainerAllocator> Type;

  SetLEDValueRequest_()
    : value(0)  {
    }
  SetLEDValueRequest_(const ContainerAllocator& _alloc)
    : value(0)  {
  (void)_alloc;
    }



   typedef int32_t _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::mirte_msgs::SetLEDValueRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mirte_msgs::SetLEDValueRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetLEDValueRequest_

typedef ::mirte_msgs::SetLEDValueRequest_<std::allocator<void> > SetLEDValueRequest;

typedef boost::shared_ptr< ::mirte_msgs::SetLEDValueRequest > SetLEDValueRequestPtr;
typedef boost::shared_ptr< ::mirte_msgs::SetLEDValueRequest const> SetLEDValueRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mirte_msgs::SetLEDValueRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mirte_msgs::SetLEDValueRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mirte_msgs::SetLEDValueRequest_<ContainerAllocator1> & lhs, const ::mirte_msgs::SetLEDValueRequest_<ContainerAllocator2> & rhs)
{
  return lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mirte_msgs::SetLEDValueRequest_<ContainerAllocator1> & lhs, const ::mirte_msgs::SetLEDValueRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mirte_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mirte_msgs::SetLEDValueRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mirte_msgs::SetLEDValueRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mirte_msgs::SetLEDValueRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mirte_msgs::SetLEDValueRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mirte_msgs::SetLEDValueRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mirte_msgs::SetLEDValueRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mirte_msgs::SetLEDValueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b3087778e93fcd34cc8d65bc54e850d1";
  }

  static const char* value(const ::mirte_msgs::SetLEDValueRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb3087778e93fcd34ULL;
  static const uint64_t static_value2 = 0xcc8d65bc54e850d1ULL;
};

template<class ContainerAllocator>
struct DataType< ::mirte_msgs::SetLEDValueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mirte_msgs/SetLEDValueRequest";
  }

  static const char* value(const ::mirte_msgs::SetLEDValueRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mirte_msgs::SetLEDValueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 value\n"
;
  }

  static const char* value(const ::mirte_msgs::SetLEDValueRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mirte_msgs::SetLEDValueRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetLEDValueRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mirte_msgs::SetLEDValueRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mirte_msgs::SetLEDValueRequest_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<int32_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MIRTE_MSGS_MESSAGE_SETLEDVALUEREQUEST_H
