// Generated by gencpp from file mirte_msgs/SetMotorSpeed.msg
// DO NOT EDIT!


#ifndef MIRTE_MSGS_MESSAGE_SETMOTORSPEED_H
#define MIRTE_MSGS_MESSAGE_SETMOTORSPEED_H

#include <ros/service_traits.h>


#include <mirte_msgs/SetMotorSpeedRequest.h>
#include <mirte_msgs/SetMotorSpeedResponse.h>


namespace mirte_msgs
{

struct SetMotorSpeed
{

typedef SetMotorSpeedRequest Request;
typedef SetMotorSpeedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetMotorSpeed
} // namespace mirte_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mirte_msgs::SetMotorSpeed > {
  static const char* value()
  {
    return "ec6a2ec4df43df120c9889aac5800d51";
  }

  static const char* value(const ::mirte_msgs::SetMotorSpeed&) { return value(); }
};

template<>
struct DataType< ::mirte_msgs::SetMotorSpeed > {
  static const char* value()
  {
    return "mirte_msgs/SetMotorSpeed";
  }

  static const char* value(const ::mirte_msgs::SetMotorSpeed&) { return value(); }
};


// service_traits::MD5Sum< ::mirte_msgs::SetMotorSpeedRequest> should match
// service_traits::MD5Sum< ::mirte_msgs::SetMotorSpeed >
template<>
struct MD5Sum< ::mirte_msgs::SetMotorSpeedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mirte_msgs::SetMotorSpeed >::value();
  }
  static const char* value(const ::mirte_msgs::SetMotorSpeedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirte_msgs::SetMotorSpeedRequest> should match
// service_traits::DataType< ::mirte_msgs::SetMotorSpeed >
template<>
struct DataType< ::mirte_msgs::SetMotorSpeedRequest>
{
  static const char* value()
  {
    return DataType< ::mirte_msgs::SetMotorSpeed >::value();
  }
  static const char* value(const ::mirte_msgs::SetMotorSpeedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mirte_msgs::SetMotorSpeedResponse> should match
// service_traits::MD5Sum< ::mirte_msgs::SetMotorSpeed >
template<>
struct MD5Sum< ::mirte_msgs::SetMotorSpeedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mirte_msgs::SetMotorSpeed >::value();
  }
  static const char* value(const ::mirte_msgs::SetMotorSpeedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirte_msgs::SetMotorSpeedResponse> should match
// service_traits::DataType< ::mirte_msgs::SetMotorSpeed >
template<>
struct DataType< ::mirte_msgs::SetMotorSpeedResponse>
{
  static const char* value()
  {
    return DataType< ::mirte_msgs::SetMotorSpeed >::value();
  }
  static const char* value(const ::mirte_msgs::SetMotorSpeedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MIRTE_MSGS_MESSAGE_SETMOTORSPEED_H
