// Generated by gencpp from file mirte_msgs/SetOLEDImageRequest.msg
// DO NOT EDIT!


#ifndef MIRTE_MSGS_MESSAGE_SETOLEDIMAGEREQUEST_H
#define MIRTE_MSGS_MESSAGE_SETOLEDIMAGEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mirte_msgs
{
template <class ContainerAllocator>
struct SetOLEDImageRequest_
{
  typedef SetOLEDImageRequest_<ContainerAllocator> Type;

  SetOLEDImageRequest_()
    : type()
    , value()  {
    }
  SetOLEDImageRequest_(const ContainerAllocator& _alloc)
    : type(_alloc)
    , value(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _type_type;
  _type_type type;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::mirte_msgs::SetOLEDImageRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mirte_msgs::SetOLEDImageRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetOLEDImageRequest_

typedef ::mirte_msgs::SetOLEDImageRequest_<std::allocator<void> > SetOLEDImageRequest;

typedef boost::shared_ptr< ::mirte_msgs::SetOLEDImageRequest > SetOLEDImageRequestPtr;
typedef boost::shared_ptr< ::mirte_msgs::SetOLEDImageRequest const> SetOLEDImageRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mirte_msgs::SetOLEDImageRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mirte_msgs::SetOLEDImageRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mirte_msgs::SetOLEDImageRequest_<ContainerAllocator1> & lhs, const ::mirte_msgs::SetOLEDImageRequest_<ContainerAllocator2> & rhs)
{
  return lhs.type == rhs.type &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mirte_msgs::SetOLEDImageRequest_<ContainerAllocator1> & lhs, const ::mirte_msgs::SetOLEDImageRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mirte_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mirte_msgs::SetOLEDImageRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mirte_msgs::SetOLEDImageRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mirte_msgs::SetOLEDImageRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mirte_msgs::SetOLEDImageRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mirte_msgs::SetOLEDImageRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mirte_msgs::SetOLEDImageRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mirte_msgs::SetOLEDImageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "438f41c8875f48b6525645ad9745bffb";
  }

  static const char* value(const ::mirte_msgs::SetOLEDImageRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x438f41c8875f48b6ULL;
  static const uint64_t static_value2 = 0x525645ad9745bffbULL;
};

template<class ContainerAllocator>
struct DataType< ::mirte_msgs::SetOLEDImageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mirte_msgs/SetOLEDImageRequest";
  }

  static const char* value(const ::mirte_msgs::SetOLEDImageRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mirte_msgs::SetOLEDImageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string type\n"
"string value\n"
;
  }

  static const char* value(const ::mirte_msgs::SetOLEDImageRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mirte_msgs::SetOLEDImageRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetOLEDImageRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mirte_msgs::SetOLEDImageRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mirte_msgs::SetOLEDImageRequest_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.type);
    s << indent << "value: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MIRTE_MSGS_MESSAGE_SETOLEDIMAGEREQUEST_H
