// Generated by gencpp from file mirte_msgs/SetOLEDImage.msg
// DO NOT EDIT!


#ifndef MIRTE_MSGS_MESSAGE_SETOLEDIMAGE_H
#define MIRTE_MSGS_MESSAGE_SETOLEDIMAGE_H

#include <ros/service_traits.h>


#include <mirte_msgs/SetOLEDImageRequest.h>
#include <mirte_msgs/SetOLEDImageResponse.h>


namespace mirte_msgs
{

struct SetOLEDImage
{

typedef SetOLEDImageRequest Request;
typedef SetOLEDImageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetOLEDImage
} // namespace mirte_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mirte_msgs::SetOLEDImage > {
  static const char* value()
  {
    return "52215026eb827c220b801bf2b2c8f4d1";
  }

  static const char* value(const ::mirte_msgs::SetOLEDImage&) { return value(); }
};

template<>
struct DataType< ::mirte_msgs::SetOLEDImage > {
  static const char* value()
  {
    return "mirte_msgs/SetOLEDImage";
  }

  static const char* value(const ::mirte_msgs::SetOLEDImage&) { return value(); }
};


// service_traits::MD5Sum< ::mirte_msgs::SetOLEDImageRequest> should match
// service_traits::MD5Sum< ::mirte_msgs::SetOLEDImage >
template<>
struct MD5Sum< ::mirte_msgs::SetOLEDImageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mirte_msgs::SetOLEDImage >::value();
  }
  static const char* value(const ::mirte_msgs::SetOLEDImageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirte_msgs::SetOLEDImageRequest> should match
// service_traits::DataType< ::mirte_msgs::SetOLEDImage >
template<>
struct DataType< ::mirte_msgs::SetOLEDImageRequest>
{
  static const char* value()
  {
    return DataType< ::mirte_msgs::SetOLEDImage >::value();
  }
  static const char* value(const ::mirte_msgs::SetOLEDImageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mirte_msgs::SetOLEDImageResponse> should match
// service_traits::MD5Sum< ::mirte_msgs::SetOLEDImage >
template<>
struct MD5Sum< ::mirte_msgs::SetOLEDImageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mirte_msgs::SetOLEDImage >::value();
  }
  static const char* value(const ::mirte_msgs::SetOLEDImageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirte_msgs::SetOLEDImageResponse> should match
// service_traits::DataType< ::mirte_msgs::SetOLEDImage >
template<>
struct DataType< ::mirte_msgs::SetOLEDImageResponse>
{
  static const char* value()
  {
    return DataType< ::mirte_msgs::SetOLEDImage >::value();
  }
  static const char* value(const ::mirte_msgs::SetOLEDImageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MIRTE_MSGS_MESSAGE_SETOLEDIMAGE_H
