// Generated by gencpp from file mirte_msgs/SetPinMode.msg
// DO NOT EDIT!


#ifndef MIRTE_MSGS_MESSAGE_SETPINMODE_H
#define MIRTE_MSGS_MESSAGE_SETPINMODE_H

#include <ros/service_traits.h>


#include <mirte_msgs/SetPinModeRequest.h>
#include <mirte_msgs/SetPinModeResponse.h>


namespace mirte_msgs
{

struct SetPinMode
{

typedef SetPinModeRequest Request;
typedef SetPinModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPinMode
} // namespace mirte_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mirte_msgs::SetPinMode > {
  static const char* value()
  {
    return "f8d9d67f15a539c1c17373473c0a782d";
  }

  static const char* value(const ::mirte_msgs::SetPinMode&) { return value(); }
};

template<>
struct DataType< ::mirte_msgs::SetPinMode > {
  static const char* value()
  {
    return "mirte_msgs/SetPinMode";
  }

  static const char* value(const ::mirte_msgs::SetPinMode&) { return value(); }
};


// service_traits::MD5Sum< ::mirte_msgs::SetPinModeRequest> should match
// service_traits::MD5Sum< ::mirte_msgs::SetPinMode >
template<>
struct MD5Sum< ::mirte_msgs::SetPinModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mirte_msgs::SetPinMode >::value();
  }
  static const char* value(const ::mirte_msgs::SetPinModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirte_msgs::SetPinModeRequest> should match
// service_traits::DataType< ::mirte_msgs::SetPinMode >
template<>
struct DataType< ::mirte_msgs::SetPinModeRequest>
{
  static const char* value()
  {
    return DataType< ::mirte_msgs::SetPinMode >::value();
  }
  static const char* value(const ::mirte_msgs::SetPinModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mirte_msgs::SetPinModeResponse> should match
// service_traits::MD5Sum< ::mirte_msgs::SetPinMode >
template<>
struct MD5Sum< ::mirte_msgs::SetPinModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mirte_msgs::SetPinMode >::value();
  }
  static const char* value(const ::mirte_msgs::SetPinModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirte_msgs::SetPinModeResponse> should match
// service_traits::DataType< ::mirte_msgs::SetPinMode >
template<>
struct DataType< ::mirte_msgs::SetPinModeResponse>
{
  static const char* value()
  {
    return DataType< ::mirte_msgs::SetPinMode >::value();
  }
  static const char* value(const ::mirte_msgs::SetPinModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MIRTE_MSGS_MESSAGE_SETPINMODE_H
