// Generated by gencpp from file mirte_msgs/SetPinValueRequest.msg
// DO NOT EDIT!


#ifndef MIRTE_MSGS_MESSAGE_SETPINVALUEREQUEST_H
#define MIRTE_MSGS_MESSAGE_SETPINVALUEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mirte_msgs
{
template <class ContainerAllocator>
struct SetPinValueRequest_
{
  typedef SetPinValueRequest_<ContainerAllocator> Type;

  SetPinValueRequest_()
    : pin()
    , type()
    , value(0)  {
    }
  SetPinValueRequest_(const ContainerAllocator& _alloc)
    : pin(_alloc)
    , type(_alloc)
    , value(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _pin_type;
  _pin_type pin;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _type_type;
  _type_type type;

   typedef int32_t _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::mirte_msgs::SetPinValueRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mirte_msgs::SetPinValueRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetPinValueRequest_

typedef ::mirte_msgs::SetPinValueRequest_<std::allocator<void> > SetPinValueRequest;

typedef boost::shared_ptr< ::mirte_msgs::SetPinValueRequest > SetPinValueRequestPtr;
typedef boost::shared_ptr< ::mirte_msgs::SetPinValueRequest const> SetPinValueRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mirte_msgs::SetPinValueRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mirte_msgs::SetPinValueRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mirte_msgs::SetPinValueRequest_<ContainerAllocator1> & lhs, const ::mirte_msgs::SetPinValueRequest_<ContainerAllocator2> & rhs)
{
  return lhs.pin == rhs.pin &&
    lhs.type == rhs.type &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mirte_msgs::SetPinValueRequest_<ContainerAllocator1> & lhs, const ::mirte_msgs::SetPinValueRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mirte_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mirte_msgs::SetPinValueRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mirte_msgs::SetPinValueRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mirte_msgs::SetPinValueRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mirte_msgs::SetPinValueRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mirte_msgs::SetPinValueRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mirte_msgs::SetPinValueRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mirte_msgs::SetPinValueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9fb05b4c0317942b9905fb1d69bb581d";
  }

  static const char* value(const ::mirte_msgs::SetPinValueRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9fb05b4c0317942bULL;
  static const uint64_t static_value2 = 0x9905fb1d69bb581dULL;
};

template<class ContainerAllocator>
struct DataType< ::mirte_msgs::SetPinValueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mirte_msgs/SetPinValueRequest";
  }

  static const char* value(const ::mirte_msgs::SetPinValueRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mirte_msgs::SetPinValueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string pin\n"
"string type\n"
"int32 value\n"
;
  }

  static const char* value(const ::mirte_msgs::SetPinValueRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mirte_msgs::SetPinValueRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pin);
      stream.next(m.type);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetPinValueRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mirte_msgs::SetPinValueRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mirte_msgs::SetPinValueRequest_<ContainerAllocator>& v)
  {
    s << indent << "pin: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.pin);
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.type);
    s << indent << "value: ";
    Printer<int32_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MIRTE_MSGS_MESSAGE_SETPINVALUEREQUEST_H
