// Generated by gencpp from file mirte_msgs/SetPinValue.msg
// DO NOT EDIT!


#ifndef MIRTE_MSGS_MESSAGE_SETPINVALUE_H
#define MIRTE_MSGS_MESSAGE_SETPINVALUE_H

#include <ros/service_traits.h>


#include <mirte_msgs/SetPinValueRequest.h>
#include <mirte_msgs/SetPinValueResponse.h>


namespace mirte_msgs
{

struct SetPinValue
{

typedef SetPinValueRequest Request;
typedef SetPinValueResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPinValue
} // namespace mirte_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mirte_msgs::SetPinValue > {
  static const char* value()
  {
    return "ca22cfaaa89cb1d56388f4014610ebb5";
  }

  static const char* value(const ::mirte_msgs::SetPinValue&) { return value(); }
};

template<>
struct DataType< ::mirte_msgs::SetPinValue > {
  static const char* value()
  {
    return "mirte_msgs/SetPinValue";
  }

  static const char* value(const ::mirte_msgs::SetPinValue&) { return value(); }
};


// service_traits::MD5Sum< ::mirte_msgs::SetPinValueRequest> should match
// service_traits::MD5Sum< ::mirte_msgs::SetPinValue >
template<>
struct MD5Sum< ::mirte_msgs::SetPinValueRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mirte_msgs::SetPinValue >::value();
  }
  static const char* value(const ::mirte_msgs::SetPinValueRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirte_msgs::SetPinValueRequest> should match
// service_traits::DataType< ::mirte_msgs::SetPinValue >
template<>
struct DataType< ::mirte_msgs::SetPinValueRequest>
{
  static const char* value()
  {
    return DataType< ::mirte_msgs::SetPinValue >::value();
  }
  static const char* value(const ::mirte_msgs::SetPinValueRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mirte_msgs::SetPinValueResponse> should match
// service_traits::MD5Sum< ::mirte_msgs::SetPinValue >
template<>
struct MD5Sum< ::mirte_msgs::SetPinValueResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mirte_msgs::SetPinValue >::value();
  }
  static const char* value(const ::mirte_msgs::SetPinValueResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirte_msgs::SetPinValueResponse> should match
// service_traits::DataType< ::mirte_msgs::SetPinValue >
template<>
struct DataType< ::mirte_msgs::SetPinValueResponse>
{
  static const char* value()
  {
    return DataType< ::mirte_msgs::SetPinValue >::value();
  }
  static const char* value(const ::mirte_msgs::SetPinValueResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MIRTE_MSGS_MESSAGE_SETPINVALUE_H
