// Generated by gencpp from file mirte_msgs/SetServoAngleRequest.msg
// DO NOT EDIT!


#ifndef MIRTE_MSGS_MESSAGE_SETSERVOANGLEREQUEST_H
#define MIRTE_MSGS_MESSAGE_SETSERVOANGLEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mirte_msgs
{
template <class ContainerAllocator>
struct SetServoAngleRequest_
{
  typedef SetServoAngleRequest_<ContainerAllocator> Type;

  SetServoAngleRequest_()
    : angle(0.0)  {
    }
  SetServoAngleRequest_(const ContainerAllocator& _alloc)
    : angle(0.0)  {
  (void)_alloc;
    }



   typedef float _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::mirte_msgs::SetServoAngleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mirte_msgs::SetServoAngleRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetServoAngleRequest_

typedef ::mirte_msgs::SetServoAngleRequest_<std::allocator<void> > SetServoAngleRequest;

typedef boost::shared_ptr< ::mirte_msgs::SetServoAngleRequest > SetServoAngleRequestPtr;
typedef boost::shared_ptr< ::mirte_msgs::SetServoAngleRequest const> SetServoAngleRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mirte_msgs::SetServoAngleRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mirte_msgs::SetServoAngleRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mirte_msgs::SetServoAngleRequest_<ContainerAllocator1> & lhs, const ::mirte_msgs::SetServoAngleRequest_<ContainerAllocator2> & rhs)
{
  return lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mirte_msgs::SetServoAngleRequest_<ContainerAllocator1> & lhs, const ::mirte_msgs::SetServoAngleRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mirte_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mirte_msgs::SetServoAngleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mirte_msgs::SetServoAngleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mirte_msgs::SetServoAngleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mirte_msgs::SetServoAngleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mirte_msgs::SetServoAngleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mirte_msgs::SetServoAngleRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mirte_msgs::SetServoAngleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2d11dcdbe5a6f73dd324353dc52315ab";
  }

  static const char* value(const ::mirte_msgs::SetServoAngleRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2d11dcdbe5a6f73dULL;
  static const uint64_t static_value2 = 0xd324353dc52315abULL;
};

template<class ContainerAllocator>
struct DataType< ::mirte_msgs::SetServoAngleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mirte_msgs/SetServoAngleRequest";
  }

  static const char* value(const ::mirte_msgs::SetServoAngleRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mirte_msgs::SetServoAngleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 angle\n"
;
  }

  static const char* value(const ::mirte_msgs::SetServoAngleRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mirte_msgs::SetServoAngleRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetServoAngleRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mirte_msgs::SetServoAngleRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mirte_msgs::SetServoAngleRequest_<ContainerAllocator>& v)
  {
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MIRTE_MSGS_MESSAGE_SETSERVOANGLEREQUEST_H
