// Generated by gencpp from file mirte_msgs/SetServoAngle.msg
// DO NOT EDIT!


#ifndef MIRTE_MSGS_MESSAGE_SETSERVOANGLE_H
#define MIRTE_MSGS_MESSAGE_SETSERVOANGLE_H

#include <ros/service_traits.h>


#include <mirte_msgs/SetServoAngleRequest.h>
#include <mirte_msgs/SetServoAngleResponse.h>


namespace mirte_msgs
{

struct SetServoAngle
{

typedef SetServoAngleRequest Request;
typedef SetServoAngleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetServoAngle
} // namespace mirte_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mirte_msgs::SetServoAngle > {
  static const char* value()
  {
    return "ac590a8a24d757d23bdd7dab963c6e6f";
  }

  static const char* value(const ::mirte_msgs::SetServoAngle&) { return value(); }
};

template<>
struct DataType< ::mirte_msgs::SetServoAngle > {
  static const char* value()
  {
    return "mirte_msgs/SetServoAngle";
  }

  static const char* value(const ::mirte_msgs::SetServoAngle&) { return value(); }
};


// service_traits::MD5Sum< ::mirte_msgs::SetServoAngleRequest> should match
// service_traits::MD5Sum< ::mirte_msgs::SetServoAngle >
template<>
struct MD5Sum< ::mirte_msgs::SetServoAngleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mirte_msgs::SetServoAngle >::value();
  }
  static const char* value(const ::mirte_msgs::SetServoAngleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirte_msgs::SetServoAngleRequest> should match
// service_traits::DataType< ::mirte_msgs::SetServoAngle >
template<>
struct DataType< ::mirte_msgs::SetServoAngleRequest>
{
  static const char* value()
  {
    return DataType< ::mirte_msgs::SetServoAngle >::value();
  }
  static const char* value(const ::mirte_msgs::SetServoAngleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mirte_msgs::SetServoAngleResponse> should match
// service_traits::MD5Sum< ::mirte_msgs::SetServoAngle >
template<>
struct MD5Sum< ::mirte_msgs::SetServoAngleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mirte_msgs::SetServoAngle >::value();
  }
  static const char* value(const ::mirte_msgs::SetServoAngleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirte_msgs::SetServoAngleResponse> should match
// service_traits::DataType< ::mirte_msgs::SetServoAngle >
template<>
struct DataType< ::mirte_msgs::SetServoAngleResponse>
{
  static const char* value()
  {
    return DataType< ::mirte_msgs::SetServoAngle >::value();
  }
  static const char* value(const ::mirte_msgs::SetServoAngleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MIRTE_MSGS_MESSAGE_SETSERVOANGLE_H
