// Generated by gencpp from file mirte_msgs/SetSingleLEDValue.msg
// DO NOT EDIT!


#ifndef MIRTE_MSGS_MESSAGE_SETSINGLELEDVALUE_H
#define MIRTE_MSGS_MESSAGE_SETSINGLELEDVALUE_H

#include <ros/service_traits.h>


#include <mirte_msgs/SetSingleLEDValueRequest.h>
#include <mirte_msgs/SetSingleLEDValueResponse.h>


namespace mirte_msgs
{

struct SetSingleLEDValue
{

typedef SetSingleLEDValueRequest Request;
typedef SetSingleLEDValueResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetSingleLEDValue
} // namespace mirte_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mirte_msgs::SetSingleLEDValue > {
  static const char* value()
  {
    return "4d6f4830182c46665b9a704973ece68d";
  }

  static const char* value(const ::mirte_msgs::SetSingleLEDValue&) { return value(); }
};

template<>
struct DataType< ::mirte_msgs::SetSingleLEDValue > {
  static const char* value()
  {
    return "mirte_msgs/SetSingleLEDValue";
  }

  static const char* value(const ::mirte_msgs::SetSingleLEDValue&) { return value(); }
};


// service_traits::MD5Sum< ::mirte_msgs::SetSingleLEDValueRequest> should match
// service_traits::MD5Sum< ::mirte_msgs::SetSingleLEDValue >
template<>
struct MD5Sum< ::mirte_msgs::SetSingleLEDValueRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mirte_msgs::SetSingleLEDValue >::value();
  }
  static const char* value(const ::mirte_msgs::SetSingleLEDValueRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirte_msgs::SetSingleLEDValueRequest> should match
// service_traits::DataType< ::mirte_msgs::SetSingleLEDValue >
template<>
struct DataType< ::mirte_msgs::SetSingleLEDValueRequest>
{
  static const char* value()
  {
    return DataType< ::mirte_msgs::SetSingleLEDValue >::value();
  }
  static const char* value(const ::mirte_msgs::SetSingleLEDValueRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mirte_msgs::SetSingleLEDValueResponse> should match
// service_traits::MD5Sum< ::mirte_msgs::SetSingleLEDValue >
template<>
struct MD5Sum< ::mirte_msgs::SetSingleLEDValueResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mirte_msgs::SetSingleLEDValue >::value();
  }
  static const char* value(const ::mirte_msgs::SetSingleLEDValueResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirte_msgs::SetSingleLEDValueResponse> should match
// service_traits::DataType< ::mirte_msgs::SetSingleLEDValue >
template<>
struct DataType< ::mirte_msgs::SetSingleLEDValueResponse>
{
  static const char* value()
  {
    return DataType< ::mirte_msgs::SetSingleLEDValue >::value();
  }
  static const char* value(const ::mirte_msgs::SetSingleLEDValueResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MIRTE_MSGS_MESSAGE_SETSINGLELEDVALUE_H
