// Generated by gencpp from file mirte_msgs/SetSingleLEDValueRequest.msg
// DO NOT EDIT!


#ifndef MIRTE_MSGS_MESSAGE_SETSINGLELEDVALUEREQUEST_H
#define MIRTE_MSGS_MESSAGE_SETSINGLELEDVALUEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mirte_msgs
{
template <class ContainerAllocator>
struct SetSingleLEDValueRequest_
{
  typedef SetSingleLEDValueRequest_<ContainerAllocator> Type;

  SetSingleLEDValueRequest_()
    : value(0)
    , pixel(0)  {
    }
  SetSingleLEDValueRequest_(const ContainerAllocator& _alloc)
    : value(0)
    , pixel(0)  {
  (void)_alloc;
    }



   typedef int32_t _value_type;
  _value_type value;

   typedef int32_t _pixel_type;
  _pixel_type pixel;





  typedef boost::shared_ptr< ::mirte_msgs::SetSingleLEDValueRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mirte_msgs::SetSingleLEDValueRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetSingleLEDValueRequest_

typedef ::mirte_msgs::SetSingleLEDValueRequest_<std::allocator<void> > SetSingleLEDValueRequest;

typedef boost::shared_ptr< ::mirte_msgs::SetSingleLEDValueRequest > SetSingleLEDValueRequestPtr;
typedef boost::shared_ptr< ::mirte_msgs::SetSingleLEDValueRequest const> SetSingleLEDValueRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mirte_msgs::SetSingleLEDValueRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mirte_msgs::SetSingleLEDValueRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mirte_msgs::SetSingleLEDValueRequest_<ContainerAllocator1> & lhs, const ::mirte_msgs::SetSingleLEDValueRequest_<ContainerAllocator2> & rhs)
{
  return lhs.value == rhs.value &&
    lhs.pixel == rhs.pixel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mirte_msgs::SetSingleLEDValueRequest_<ContainerAllocator1> & lhs, const ::mirte_msgs::SetSingleLEDValueRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mirte_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mirte_msgs::SetSingleLEDValueRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mirte_msgs::SetSingleLEDValueRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mirte_msgs::SetSingleLEDValueRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mirte_msgs::SetSingleLEDValueRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mirte_msgs::SetSingleLEDValueRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mirte_msgs::SetSingleLEDValueRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mirte_msgs::SetSingleLEDValueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "71a0908698450e1660a38892bf901bac";
  }

  static const char* value(const ::mirte_msgs::SetSingleLEDValueRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x71a0908698450e16ULL;
  static const uint64_t static_value2 = 0x60a38892bf901bacULL;
};

template<class ContainerAllocator>
struct DataType< ::mirte_msgs::SetSingleLEDValueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mirte_msgs/SetSingleLEDValueRequest";
  }

  static const char* value(const ::mirte_msgs::SetSingleLEDValueRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mirte_msgs::SetSingleLEDValueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 value\n"
"int32 pixel\n"
;
  }

  static const char* value(const ::mirte_msgs::SetSingleLEDValueRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mirte_msgs::SetSingleLEDValueRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
      stream.next(m.pixel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetSingleLEDValueRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mirte_msgs::SetSingleLEDValueRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mirte_msgs::SetSingleLEDValueRequest_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<int32_t>::stream(s, indent + "  ", v.value);
    s << indent << "pixel: ";
    Printer<int32_t>::stream(s, indent + "  ", v.pixel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MIRTE_MSGS_MESSAGE_SETSINGLELEDVALUEREQUEST_H
