// Generated by gencpp from file mirte_msgs/TurnRequest.msg
// DO NOT EDIT!


#ifndef MIRTE_MSGS_MESSAGE_TURNREQUEST_H
#define MIRTE_MSGS_MESSAGE_TURNREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mirte_msgs
{
template <class ContainerAllocator>
struct TurnRequest_
{
  typedef TurnRequest_<ContainerAllocator> Type;

  TurnRequest_()
    : angle(0.0)
    , speed(0.0)  {
    }
  TurnRequest_(const ContainerAllocator& _alloc)
    : angle(0.0)
    , speed(0.0)  {
  (void)_alloc;
    }



   typedef float _angle_type;
  _angle_type angle;

   typedef float _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::mirte_msgs::TurnRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mirte_msgs::TurnRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TurnRequest_

typedef ::mirte_msgs::TurnRequest_<std::allocator<void> > TurnRequest;

typedef boost::shared_ptr< ::mirte_msgs::TurnRequest > TurnRequestPtr;
typedef boost::shared_ptr< ::mirte_msgs::TurnRequest const> TurnRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mirte_msgs::TurnRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mirte_msgs::TurnRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mirte_msgs::TurnRequest_<ContainerAllocator1> & lhs, const ::mirte_msgs::TurnRequest_<ContainerAllocator2> & rhs)
{
  return lhs.angle == rhs.angle &&
    lhs.speed == rhs.speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mirte_msgs::TurnRequest_<ContainerAllocator1> & lhs, const ::mirte_msgs::TurnRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mirte_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mirte_msgs::TurnRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mirte_msgs::TurnRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mirte_msgs::TurnRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mirte_msgs::TurnRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mirte_msgs::TurnRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mirte_msgs::TurnRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mirte_msgs::TurnRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "baf76ae04cb33f72ceb96ed255b76ef4";
  }

  static const char* value(const ::mirte_msgs::TurnRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbaf76ae04cb33f72ULL;
  static const uint64_t static_value2 = 0xceb96ed255b76ef4ULL;
};

template<class ContainerAllocator>
struct DataType< ::mirte_msgs::TurnRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mirte_msgs/TurnRequest";
  }

  static const char* value(const ::mirte_msgs::TurnRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mirte_msgs::TurnRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 angle       # rad\n"
"float32 speed       # rad/s\n"
;
  }

  static const char* value(const ::mirte_msgs::TurnRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mirte_msgs::TurnRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TurnRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mirte_msgs::TurnRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mirte_msgs::TurnRequest_<ContainerAllocator>& v)
  {
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MIRTE_MSGS_MESSAGE_TURNREQUEST_H
