obstacle_range: 2.5
raytrace_range: 3.0
# footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
robot_radius: 0.2
inflation_radius: 0.2

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: mirtebot_0/lidar_link, data_type: LaserScan, topic: mirtebot_0/scan, marking: true, clearing: true}
